apiVersion: v1
kind: Service
metadata:
  name: {{ include "sajchart.fullname" . }}
  labels:
    {{- include "sajchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.labels.app }}
    type: {{ .Values.labels.type }}  
